### ISSUE TITLE
Writing of objects to local storage broken in 0.1.6 w/ Blazor 0.7.0

### ISSUE THREAD

**Issue by ransagy** [BlazorExtensions/Storage#13]
Since upgrading to Blazor 0.6.0 to 0.7.0 and from Storage 0.1.5 to 0.1.6, Writing objects directly to local storage seems broken.

i.e. Doing this:
```csharp
storage.SetItem($"MyAppName.{nameof(MyClassName).ToLower()}", myClassInstance);
```
in 0.1.5 resulted in something like `{ \"Id\": 1337 }` being saved to storage, where as in 0.1.6 it only writes `[object Object]` instead.
Downgrading back to 0.1.5 (but still with Blazor 0.7.0) works as expected.

**Comment by galvesribeiro** [comment]
Totally related to https://github.com/BlazorExtensions/Storage/pull/10

Will revert it as soon as I get back. I should tested the PR... I only eye-reviewed it, sorry about that...

**Comment by galvesribeiro** [comment]
Hey @ransagy 

Did that got fixed on the last updates?

**Comment by ransagy** [comment]
@galvesribeiro Still the same for me on Blazor 0.7.0 with 0.1.7.

**Comment by galvesribeiro** [comment]
Updated to preview4, can you try with it?

**Comment by ransagy** [comment]
I have yet to update my apps for preview4; It's proving harder than the previous ones. I'll try to get to it in the next day or two and report back.

**Comment by ransagy** [comment]
@galvesribeiro Confirmed working fine in 0.1.8 + 3.0 preview.5 - Closed.
