### ISSUE TITLE
Calling SessionStorage.GetItem<> in OnInitAsync method makes browser freeze

### ISSUE THREAD

**Issue by stas-sultanov** [BlazorExtensions/Storage#14]
following code

```
protected override async Task OnInitAsync()
{
	var entity = await Storage.GetItem<TL.KnowledgeBase.Entity>("entity");

	if (entity == null)
		entity = new TL.KnowledgeBase.Entity();
}
```

makes browser freeze

Blazor 0.7

**Comment by galvesribeiro** [comment]
Please try the new version of the package which should be out on NuGet in a couple of minutes.

![image](https://user-images.githubusercontent.com/4714040/49012339-3e596300-f160-11e8-9564-a4220cc74be5.png)
