### ISSUE TITLE
JSException in Blazor 0.8

### ISSUE THREAD

**Issue by MorneZaayman** [BlazorExtensions/Storage#18]
When using the extension in Blazor 0.8 the follow exception is thrown:

`[Microsoft.JSInterop.JSException] Could not find 'BlazorExtensions' in 'window'.`

**Comment by galvesribeiro** [comment]
Blazor 0.8.0 is not yet supported. I'll update the packages soon.

**Comment by andras-ferencz** [comment]
As a really bad workaround you can upgrade the project to 0.8 manually and then copy and paste the content of ~/_content/Blazor.Extensions.Storage.js into your index.html inside of a script tag.

**Comment by McHeff** [comment]
PLEASE update as soon as you get this working in Blazor 0.8, keen to see it in action. 

In the meantime, you're welcome to join our discord server for Blazor: https://discord.gg/Xg9ja5s

**Comment by galvesribeiro** [comment]
Updated to preview4, please try latest packages
