### ISSUE TITLE
Installing this in an 0.9.0 app causes the app to break.

### ISSUE THREAD

**Issue by shawty** [BlazorExtensions/Storage#21]
Because of the fixed reference to Blazor 0.7.0 when you try to use this in a newer 0.9.0 app from Visual Studio 2019 it causes a conflict due to the installation of the Blazor Browser run-time 0.7.0

Basically you'll see this:
![image](https://user-images.githubusercontent.com/1876454/55555950-4ca32700-56de-11e9-9b8f-65b8c5c63eed.png)

as soon as you accept the license.

And your Program.cs will show as this:
![image](https://user-images.githubusercontent.com/1876454/55556021-7a886b80-56de-11e9-9304-0b87ba360b17.png)

Cheers
Shawty

**Comment by galvesribeiro** [comment]
Updated to preview4, please try the new packages. We can re-open if you still have issues. Thanks!

**Comment by shawty** [comment]
Awesome, I'll test it later.  Right Now I'm trying to persuade EFCore to work under preview4 on the rPI. :-)
