### ISSUE TITLE
Latest commit (PR 22): Under Netstandard 3.0: Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Blazor.Extensions.Storage.SessionStorage'

### ISSUE THREAD

**Issue by aford22** [BlazorExtensions/Storage#24]
Using .net core 3 preview 4 and your latest commit of PR22, injecting LocalStorage into my class using DI results in error:

**Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Blazor.Extensions.Storage.LocalStorage'**

I believe this is because your StorageExtensions.cs calls:
```AddSingleton<LocalStorage>()```

But when your LocalStorage.cs constructor injects IJSRuntime `public LocalStorage(IJSRuntime Runtime)` I am guessing that IJSRuntime is added to the Service Collection as Scoped, therefore consuming it from your Singleton StorageExtensions.cs cases this error.

FYI I have tried amending your StorageExtensions.cs to read: `AddScoped<LocalStorage>()`. This does compile and run but then any call to `await _localStorage.SetItem<>()` never returns...

**Comment by galvesribeiro** [comment]
Can you check if that still happen with the latest package?

**Comment by aford22** [comment]
Hello. Yes I removed my assembly references and added your latest package 0.1.8. Exactly the same error as above:

Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Blazor.Extensions.Storage.LocalStorage'

**Comment by dieterdp** [comment]
same problem here, but i am using preview 5

**Comment by astecenko** [comment]
same problem to

**Comment by BlackFenix2** [comment]
It looks like an issue here

```
blazor.server.js:15 [2019-05-17T21:06:00.715Z] Error: Microsoft.JSInterop.JSException: Could not find 'BlazorExtensions' in 'window'.
Error: Could not find 'BlazorExtensions' in 'window'.
    at https://localhost:44391/_framework/blazor.server.js:8:20878
    at Array.forEach (<anonymous>)
    at d (https://localhost:44391/_framework/blazor.server.js:8:20839)
    at https://localhost:44391/_framework/blazor.server.js:8:21429
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44391/_framework/blazor.server.js:8:21403)
    at https://localhost:44391/_framework/blazor.server.js:1:16653
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44391/_framework/blazor.server.js:1:16624)
    at e.processIncomingData (https://localhost:44391/_framework/blazor.server.js:1:14624)
   at BlazorTest.Components.Shared.UserProvider.OnAfterRenderAsync() in C:\Users\efrancis\Source\Repos\BlazorTest\BlazorTest\Components\Shared\UserProvider.razor:line 40
   at Microsoft.AspNetCore.Components.Rendering.Renderer.GetErrorHandledTask(Task taskToHandle)
```

I forked this repo and ill try to make a PR that works with Preview 5

**Comment by cpsaez-Lendsum** [comment]
I have the same problem here:

> 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Blazor.Extensions.Storage.SessionStorage Lifetime: Singleton ImplementationType: Blazor.Extensions.Storage.SessionStorage': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Blazor.Extensions.Storage.SessionStorage'.) (Error while validating the service descriptor 'ServiceType: Blazor.Extensions.Storage.LocalStorage Lifetime: Singleton ImplementationType: Blazor.Extensions.Storage.LocalStorage': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Blazor.Extensions.Storage.LocalStorage

Using .net core sdk preview 5 and extensions.storage 0.1.8 in a **server side project.**

**Comment by cpsaez-Lendsum** [comment]
After a couple of hours I can execute it in server mode. How:

install nuget package
configure dependencies by hand using Transient scope:
`
            services.AddTransient<LocalStorage>();`

Clone this repo
Compile with typescript the ts files in Storage\src\Blazor.Extensions.Storage.JS\src
create a javascript file join both created files. I removed the 'required' to put all code togheter:

`"use strict";
//Object.defineProperty(exports, "__esModule", { value: true });

class BrowserStorage {
    Length(storage) {
        return window[storage].length;
    }
    ;
    Key(storage, index) {
        return window[storage].key(index);
    }
    ;
    GetItem(storage, key) {
        const item = window[storage].getItem(key);
        if (item) {
            return JSON.parse(item);
        }
        return null;
    }
    ;
    SetItem(storage, key, keyValue) {
        window[storage].setItem(key, JSON.stringify(keyValue));
    }
    ;
    RemoveItem(storage, key) {
        window[storage].removeItem(key);
    }
    ;
    Clear(storage) {
        window[storage].clear();
    }
    ;
}


var Storage;
(function (Storage) {
    const blazorExtensions = 'BlazorExtensions';
    const extensionObject = {
        Storage: new BrowserStorage()
    };
    function initialize() {
        if (typeof window !== 'undefined' && !window[blazorExtensions]) {
            window[blazorExtensions] = Object.assign({}, extensionObject);
        }
        else {
            window[blazorExtensions] = Object.assign({}, window[blazorExtensions], extensionObject);
        }
    }
    Storage.initialize = initialize;
})(Storage || (Storage = {}));
Storage.initialize();`

I named this file InitializeStorage.js (very original I know)

Reference this file in _Host.cshtml at the end of the body part:

`<body id="page-top">
    <app>@(await Html.RenderComponentAsync<App>())</app>
    <script src="_framework/blazor.server.js"></script>
    **<script src="~/assets/js/InitializeStorage.js"></script>**
</body>`

And it started to work. I figured it out the problem to "embed" javascript code from external dll. But this trick works for me. No idea how to contribute and fix this issue once for all.

**Comment by seanmorangsp** [comment]
Same with preview 7.

**Comment by galvesribeiro** [comment]
I just tested now with both Scoped and Singleton and both works. I'm change it to scoped just for the sake of being compliant with the JS runtime registration. Also yes, it works on preview7. Please check the pictures below.

![image](https://user-images.githubusercontent.com/4714040/62241817-497c2700-b3b0-11e9-8bd3-b6826f9e58c8.png)
![image](https://user-images.githubusercontent.com/4714040/62241846-5b5dca00-b3b0-11e9-88b4-e72981592a3e.png)
![image](https://user-images.githubusercontent.com/4714040/62241889-69134f80-b3b0-11e9-8301-d79d9544f822.png)
![image](https://user-images.githubusercontent.com/4714040/62241909-77fa0200-b3b0-11e9-8c6f-01718797cd22.png)
![image](https://user-images.githubusercontent.com/4714040/62241956-965ffd80-b3b0-11e9-9f3b-cf6c6c00cb5c.png)

**Comment by galvesribeiro** [comment]
The package was published https://www.nuget.org/packages/Blazor.Extensions.Storage/0.2.1

Nuget is indexing and it should be available soon.
