### ISSUE TITLE
Extra double-quotes when `SetItem` a string?

### ISSUE THREAD

**Issue by datvm** [BlazorExtensions/Storage#28]
Not sure if this is intended, but when I try to use `SetItem` with a string:

`await this.storage.SetItem("jwt", "hello");`

The result of Javascript `sessionStorage.jwt` is `"hello"` (the double quotes is inside the string, string length is 7).

I guess because it always uses JSON. True that `this.storage.GetItem<string>("jwt")` returns correct string but it makes us need to be careful when reading from Javascript.

**Comment by galvesribeiro** [comment]
This issue was fixed long ago. Please check the latest packages. Thanks!
