### ISSUE TITLE
Add support for preview 9

### ISSUE THREAD

**Issue by Micrypto** [BlazorExtensions/Storage#38]
Please add support for preview 9.

**Comment by smartprogrammer93** [comment]
on preview 9 it's broken

**Comment by andrewwilkin** [comment]
I know it is still in preview, but wonder when they will stop tinkering issue being this:
> Update implementations of IJSRuntime to return ValueTask<T>.

[https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/)

**Comment by smartprogrammer93** [comment]
@andrewwilkin preview literally mean they can do whatever they want. since preview means it is not ready for use. once it is GA released (3.0.0 for server side) and (5.0.0) for client side. then you can expect near 0 breaking changes in minor versions.

**Comment by Micrypto** [comment]
This is done, so I'm closing the issue.
