### ISSUE TITLE
Expose the `length` property and iterator on storage interfaces

### ISSUE THREAD

**Issue by ebekker** [BlazorExtensions/Storage#4]
Shouldn't the `length` and natural JS iterators of the storage interfaces be exposed to make the interfaces more useful?

Currently the interfaces give you the basic read/write access, but you have to know all the keys you want to work with in advance.  There is the `Key(int)` method that returns the key at a given index, but the user needs to know in advance what the length is.

By exposing a length property of the storage items, the item keys can be safely iterated, and by exposing the iterator, the keys themselves can be enumerated directly.

**Comment by ebekker** [comment]
Ah, looks like the `length` is already in there for SessionStorage, just missing for LocalStorage?

**Comment by galvesribeiro** [comment]
Good catch! Thanks for the PR, it is merged now.
