### ISSUE TITLE
Using "Wait" or "Result" in the constructor for an injected class hangs the browser.

### ISSUE THREAD

**Issue by DarrellBailey** [BlazorExtensions/Storage#43]
When using "Wait" or "Result" in the constructor for a class that uses the LocalStorage object, the browser will hang and eat large amounts of CPU.

To reproduce:

1. Create a new Blazor WebAssembly project from the official templates.
2. In the "Pages" folder, create a new file named "Counter.razor.cs"
3. Copy the following code into that class:

```
using Blazor.Extensions.Storage;
using Microsoft.AspNetCore.Components;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlazorApp1.Pages
{
    public partial class Counter
    {
        [Inject]
        public TestService TestService { get; set; }

        protected override async Task OnInitializedAsync()
        {
            var item = await TestService.AsyncMethod();

            await base.OnInitializedAsync();
        }
    }

    public class TestService
    {
        protected LocalStorage _localStorage { get; set; }

        public TestService(LocalStorage localStorage)
        {
            _localStorage = localStorage;

            //string item = AsyncMethod().Result;
        }

        public async Task<string> AsyncMethod()
        {
            return await _localStorage.GetItem<string>("key");
        }
    }
}
```
4. Uncomment the line `string item = AsyncMethod().Result;`, start the app, and navigate to the page.

The "correct" way of doing this is to use the "OnInitializedAsync" override as I have done in the example, but no other Blazor library hangs the browser in this way so I thought I would report it.

**Comment by galvesribeiro** [comment]
Hey!

Sorry for the delay.

You shouldn't use `Wait()` or `Result` at all. That will block the task scheduler and particularly o Blazor case, you will block the browser!

So, you should use the [LifeCycle events](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lifecycle-methods) to call some async method when the component is loading.

I'm closing it as it is not an issue with the component.
